version: "3.7"

services:
  mysql:
    container_name: mysql_server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - project_php
  app_project:
    container_name: PhpLaravel5APp
    build:
      context: .
      dockerfile: Dockerfile
    image: projectlaravel5:1.0
    ports:
      - 9000:9000
    depends_on:
      - mysql
    networks:
      - project_php

networks:
  project_php:
    name: project_php

